# -*- coding: utf-8 -*-
"""V1_Trabajo_N2_FUNDAMENTOS_(C_ABRIGO_C_HERRERA_K_URBINA).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1frNeiM3FbX6e8sxWGCXs-k_6FqA5Jq7q
"""

# PROYECTO 3: PREDICCIÓN DEL VALOR DE PROPIEDADES EN MELBOURNE (2016 -> 2017)
# ASIGNATURA: FUNDAMENTOS EN CIENCIA DE DATOS (MACI 2026)
# AUTORES: C. ABRIGO, C. HERRERA, K. URBINA


# 1. INTRODUCCIÓN Y DEFINICIÓN DEL PROBLEMA

# ### ¿Qué vamos a hacer?
# Se formula formalmente el problema de modelamiento predictivo inmobiliario en la ciudad de
# Melbourne, Australia, a partir de una base de datos histórica de 13.580 registros residenciales.

# ### ¿Por qué lo hacemos?
# Siguiendo la definición de la Tarea T2 y el enfoque de Fundamentos en Ciencia de Datos,
# el reto no es una partición aleatoria sintética, sino una **predicción fuera de muestra temporal**:
# entrenar modelos predictivos usando exclusivamente transacciones de 2016 y evaluar su capacidad de
# generalización en transacciones observadas en 2017. La variable objetivo es el precio en dólares (`Price`).
# La tasación errónea genera riesgos financieros severos para compradores, tasadores e instituciones bancarias.

# ### Clasificación del Problema:
# Corresponde a un problema de **Aprendizaje Supervisado de Regresión**, evaluado mediante
# validación temporal (*out-of-time evaluation*).


# 1.1. Importación de Librerías del Ecosistema Científico de Python
import sys
import warnings
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

# Componentes de Scikit-Learn para preprocesamiento y modelado
from sklearn.compose import ColumnTransformer
from sklearn.dummy import DummyRegressor
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import KFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.tree import DecisionTreeRegressor

# Configuración de visualización y advertencias
warnings.filterwarnings('ignore')
sns.set_theme(style='whitegrid')
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['font.size'] = 11

RANDOM_STATE = 42


# 2. COMPRENSIÓN Y CARGA DE LA BASE DE DATOS

# ¿Qué vamos a hacer?
# Cargar la base de datos `housing_data.csv`, inspeccionar dimensiones originales,
# homogeneizar los nombres de columnas a español (según el trabajo previo) y verificar tipos de datos.

# ¿Por qué lo hacemos?
# Para certificar la integridad del dataset real y asegurar absoluta reproducibilidad metodológica
# sin inventar valores ni variables.


# 2.1. Carga de Datos
DATA_PATH = Path('housing_data.csv')
if not DATA_PATH.exists():
  # Búsqueda de contingencia en rutas locales habituales
  DATA_PATH = Path('/content/housing_data.csv')

df = pd.read_csv(DATA_PATH)
print(f'Dimensiones del dataset cargado: {df.shape[0]:,} filas x {df.shape[1]} columnas.')

# Renombrado de columnas a español (heredado y estandarizado del Hito 1)
diccionario_columnas = {
    'Suburb': 'Barrio',
    'Address': 'Dirección',
    'Rooms': 'Habitaciones',
    'Type': 'Tipo',
    'Price': 'Precio',
    'Method': 'Método',
    'SellerG': 'Vendedor',
    'Date': 'Fecha',
    'Distance': 'Distancia',
    'Postcode': 'Postcode',
    'Bedroom2': 'Habitaciones2',
    'Bathroom': 'Baños',
    'Car': 'Automóviles',
    'Landsize': 'Tamaño_Tierra',
    'BuildingArea': 'Tamaño_Construcción',
    'YearBuilt': 'Año_Construcción',
    'CouncilArea': 'Comuna',
    'Lattitude': 'Latitud',
    'Longtitude': 'Longitud',
    'Regionname': 'Región',
    'Propertycount': 'Cantidad_Propiedades',
}
df.rename(columns=diccionario_columnas, inplace=True)

# Homogeneización de categorías de 'Tipo' y 'Método'
df['Tipo'] = df['Tipo'].replace(
    {'h': 'casa', 't': 'casapareada', 'u': 'duplex'}
)
df['Método'] = df['Método'].replace({
    'S': 'Vendida',
    'SP': 'Vendida_anteriormente',
    'PI': 'Pasada_en_remate',
    'VB': 'Oferta_vendedor',
    'SA': 'Rematada',
})

# Conversión estricta de Fecha y extracción del año
df['Fecha'] = pd.to_datetime(df['Fecha'], dayfirst=True)
df['Year'] = df['Fecha'].dt.year

print('\nDistribución de registros por año (partición objetivo):')
print(df['Year'].value_counts().sort_index())


# Resultado e Interpretación:
# - Se verifican exactamente **13.580 observaciones** y **21 atributos**.
# - La partición natural por año arroja: **6.336 registros en 2016** (46,66%) y **7.244 registros en 2017** (53,34%).
# - Rango temporal: 28 de enero de 2016 al 23 de septiembre de 2017. El año 2017 representa una muestra truncada a septiembre.


# # 3. ANÁLISIS EXPLORATORIO DE DATOS (EDA) Y AUDITORÍA DE CALIDAD

# ¿Qué vamos a hacer?
# Evaluar la presencia de datos nulos, inconsistencias en rangos, distribución de la variable objetivo
# y divergencias estructurales entre 2016 y 2017.

# ¿Por qué lo hacemos?
# Para fundamentar con evidencia cuantitativa qué variables son aptas para modelar y anticipar
# los desafíos de generalización temporal.


# 3.1. Auditoría de Valores Faltantes
tabla_nulos = pd.DataFrame(
    {'Nulos': df.isna().sum(), 'Porcentaje (%)': (df.isna().mean() * 100).round(2)}
).sort_values(by='Nulos', ascending=False)
print('Tabla de Valores Nulos:')
print(tabla_nulos[tabla_nulos['Nulos'] > 0])

# 3.2. Estadísticas de la Variable Objetivo: Precio
p_stats = df['Precio'].describe(percentiles=[0.25, 0.5, 0.75])
p_iqr = p_stats['75%'] - p_stats['25%']
print(f"\nPrecio: Media = ${p_stats['mean']:,.2f} | Mediana = ${p_stats['50%']:,.2f} | IQR = ${p_iqr:,.2f}")

# 3.3. Análisis de Composición y Novedad Territorial: 2016 vs. 2017
barrios_2016 = set(df[df['Year'] == 2016]['Barrio'].unique())
barrios_2017 = set(df[df['Year'] == 2017]['Barrio'].unique())
barrios_nuevos_2017 = barrios_2017 - barrios_2016
print(f'\nCantidad de barrios distintos en 2016: {len(barrios_2016)}')
print(f'Cantidad de barrios distintos en 2017: {len(barrios_2017)}')
print(f'Barrios observados en 2017 que NO existían en 2016: {len(barrios_nuevos_2017)} barrios nuevos.')


# Principales Hallazgos del EDA:
# 1. Concentración masiva de vacíos:** El 97,2% de los datos faltantes se concentran en `Tamaño_Construcción` (47,50%), `Año_Construcción` (39,58%) y `Comuna` (10,08%). Estas dos primeras variables se descartan para evitar la atrición del 50% de la muestra o imputaciones arbitrarias.
# 2. Asimetría positiva severa del Precio:** La media (\$1.075.684) es un 19,1% superior a la mediana (\$903.000), con un máximo de \$9.000.000. La mediana constituye el estimador de tendencia central no sesgado y la referencia obligada para el baseline.
# 3. Redundancia crítica:** `Habitaciones` y `Habitaciones2` presentan correlación lineal de $0,944$. Se descarta `Habitaciones2` para mitigar la multicolinealidad.
# 4. Desplazamiento geográfico (Covariate Shift):** En 2017 aparecen **172 barrios no vistos en 2016**. Si se utilizara `Barrio` como variable predictiva One-Hot, el modelo fallaría en Test. Por tanto, la ubicación se modela a través de variables espaciales continuas (`Distancia`, `Latitud`, `Longitud`) y la variable categórica agregada `Región`.


# 4. PREPARACIÓN DE DATOS Y PARTICIÓN TEMPORAL ESTRICTA

# ¿Qué vamos a hacer?
# Definir la matriz de predictores $X$ y el vector objetivo $y$, separando estrictamente
# por el año cronológico: 2016 para Entrenamiento y 2017 para Evaluación de Prueba (Test).

# ¿Por qué lo hacemos?
# Para cumplir el mandato de la Tarea T2 y prevenir el *data leakage*. Si se aplicara una partición aleatoria,
# transacciones del futuro contaminarían el entrenamiento.

# 4.1. Selección de Variables Predictoras Justificadas
variables_numericas = [
    'Habitaciones',
    'Baños',
    'Automóviles',
    'Distancia',
    'Tamaño_Tierra',
    'Latitud',
    'Longitud',
    'Cantidad_Propiedades',
]

variables_categoricas = [
    'Tipo',
    'Método',
    'Región',
]

features_seleccionadas = variables_numericas + variables_categoricas

# Partición temporal estricta
train_mask = df['Year'] == 2016
test_mask = df['Year'] == 2017

X_train = df.loc[train_mask, features_seleccionadas]
y_train = df.loc[train_mask, 'Precio']

X_test = df.loc[test_mask, features_seleccionadas]
y_test = df.loc[test_mask, 'Precio']

print(f'Muestra de Entrenamiento (2016): {X_train.shape[0]:,} observaciones.')
print(f'Muestra de Evaluación Test (2017): {X_test.shape[0]:,} observaciones.')


# 5. PIPELINE DE PREPROCESAMIENTO Y CONTROL DE DATA LEAKAGE

# ¿Qué vamos a hacer?
# Construir un `ColumnTransformer` que encapsule:
# - Imputación numérica con mediana calculada exclusivamente en Train.
# - Escalado estándar (`StandardScaler`) para algoritmos sensibles a distancias.
# - Codificación One-Hot para variables categóricas con control de categorías no vistas (`handle_unknown='ignore'`).

# ¿Por qué lo hacemos?
# Evita la filtración de información de Test hacia Train. Cualquier parámetro estadístico
# (media, mediana, desviación) debe ser aprendido únicamente del conjunto de 2016.


# 5.1. Construcción del Preprocesador
preprocesador = ColumnTransformer(
    transformers=[
        (
            'num',
            Pipeline(
                steps=[
                    ('imputer', SimpleImputer(strategy='median')),
                    ('scaler', StandardScaler()),
                ]
            ),
            variables_numericas,
        ),
        (
            'cat',
            Pipeline(
                steps=[
                    (
                        'imputer',
                        SimpleImputer(strategy='constant', fill_value='missing'),
                    ),
                    (
                        'encoder',
                        OneHotEncoder(
                            handle_unknown='ignore', sparse_output=False
                        ),
                    ),
                ]
            ),
            variables_categoricas,
        ),
    ]
)


# 6. DEFINICIÓN DEL BASELINE Y MODELOS CANDIDATOS

# ¿Qué vamos a hacer?
# Definir y evaluar cuatro enfoques:
# 1. Baseline:** `DummyRegressor(strategy='median')`.
# 2. Regresión Lineal Múltiple:** Modelo paramétrico interpretable de referencia.
# 3. Árbol de Decisión:** Modelo no lineal de particionamiento recursivo.
# 4. Random Forest Regressor:** Ensamble de embolsamiento (*bagging*) con reducción de varianza.
# 5. Gradient Boosting Regressor:** Ensamble de potenciación (*boosting*) que optimiza residuales de forma secuencial.

# ¿Por qué lo hacemos?
# Para determinar si la complejidad de modelos no lineales justifica su costo computacional
# frente a modelos lineales y si superan verdaderamente a la heurística base.


# 6.1. Diccionario de Modelos Integrados en Pipelines
modelos = {
    'Baseline (Mediana 2016)': DummyRegressor(strategy='median'),
    'Regresión Lineal': Pipeline(
        steps=[('prep', preprocesador), ('reg', LinearRegression())]
    ),
    'Árbol de Decisión': Pipeline(
        steps=[
            ('prep', preprocesador),
            (
                'reg',
                DecisionTreeRegressor(
                    max_depth=10, min_samples_leaf=15, random_state=RANDOM_STATE
                ),
            ),
        ]
    ),
    'Random Forest': Pipeline(
        steps=[
            ('prep', preprocesador),
            (
                'reg',
                RandomForestRegressor(
                    n_estimators=150,
                    max_depth=16,
                    min_samples_leaf=5,
                    n_jobs=-1,
                    random_state=RANDOM_STATE,
                ),
            ),
        ]
    ),
    'Gradient Boosting': Pipeline(
        steps=[
            ('prep', preprocesador),
            (
                'reg',
                GradientBoostingRegressor(
                    n_estimators=150,
                    max_depth=6,
                    learning_rate=0.08,
                    random_state=RANDOM_STATE,
                ),
            ),
        ]
    ),
}


# 7. VALIDACIÓN CRUZADA Y EVALUACIÓN FINAL EN TEST (2017)

# ¿Qué vamos a hacer?
# 1. Ejecutar validación cruzada ($K=5$) sobre el set de Train 2016 para auditar estabilidad interna.
# 2. Ajustar los modelos con la totalidad de 2016 y predecir el set de Test 2017.
# 3. Calcular métricas clave: MAE, RMSE y $R^2$.


# 7.1. Bucle de Entrenamiento y Evaluación Sistemática
cv = KFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
resultados_lista = []

print('Ejecutando validación cruzada y evaluación en Test 2017...\n')

for nombre, modelo in modelos.items():
  # Validación cruzada sobre Train 2016 usando R2 y MAE negativo
  if nombre == 'Baseline (Mediana 2016)':
    cv_r2_mean = 0.0
    modelo.fit(X_train[['Habitaciones']], y_train)
    y_pred_train = modelo.predict(X_train[['Habitaciones']])
    y_pred_test = modelo.predict(X_test[['Habitaciones']])
  else:
    scores_cv = cross_val_score(
        modelo, X_train, y_train, cv=cv, scoring='r2', n_jobs=-1
    )
    cv_r2_mean = scores_cv.mean()

    # Ajuste en Train 2016 completo
    modelo.fit(X_train, y_train)
    y_pred_train = modelo.predict(X_train)
    y_pred_test = modelo.predict(X_test)

  # Métricas de Entrenamiento (2016)
  r2_train = r2_score(y_train, y_pred_train)
  mae_train = mean_absolute_error(y_train, y_pred_train)
  rmse_train = np.sqrt(mean_squared_error(y_train, y_pred_train))

  # Métricas de Evaluación Fuera de Muestra (Test 2017)
  r2_test = r2_score(y_test, y_pred_test)
  mae_test = mean_absolute_error(y_test, y_pred_test)
  rmse_test = np.sqrt(mean_squared_error(y_test, y_pred_test))

  resultados_lista.append({
      'Modelo': nombre,
      'R² CV (Train 16)': round(cv_r2_mean, 4),
      'R² Train': round(r2_train, 4),
      'R² Test (2017)': round(r2_test, 4),
      'MAE Test ($)': round(mae_test, 2),
      'RMSE Test ($)': round(rmse_test, 2),
      'Δ R² (Train-Test)': round(r2_train - r2_test, 4),
  })

# 7.2. Tabla Comparativa Final
tabla_resultados = pd.DataFrame(resultados_lista)
print('================ TABLA COMPARATIVA DE DESEMPEÑO ================')
print(tabla_resultados.to_string(index=False))


# 8. SELECCIÓN DEL MODELO FINAL Y DIAGNÓSTICO DE RESIDUOS

# ¿Por qué elegimos Random Forest?
# 1. Capacidad predictiva superior:** Alcanza el mayor $R^2$ en Test ($0,7158$) y minimiza el MAE a **\$212.441 AUD**, superando con contundencia a la Regresión Lineal ($R^2 = 0,5934$, MAE = \$271.850 AUD).
# 2. Reducción sustancial del error frente al Baseline:** Reduce el MAE de Test en un **47,2%** respecto al predictor ciego de la mediana (\$402.138 AUD).
# 3. Estabilidad y generalización:** Aunque Gradient Boosting obtiene métricas cercanas, Random Forest presenta menor sensibilidad a hiperparámetros y resiste mejor el desplazamiento geográfico de 2017.


# 8.1. Diagnóstico Gráfico del Modelo Seleccionado (Random Forest)
rf_modelo = modelos['Random Forest']
y_pred_rf = rf_modelo.predict(X_test)
residuos = y_test - y_pred_rf

fig, ax = plt.subplots(1, 2, figsize=(16, 6))

# Gráfico 1: Real vs. Predicho
ax[0].scatter(y_test / 1e6, y_pred_rf / 1e6, alpha=0.3, color='steelblue', edgecolor='none')
ax[0].plot([0, 9], [0, 9], '--r', linewidth=2, label='Predicción Perfecta (y = x)')
ax[0].set_title('Valor Observado vs. Predicho en Test 2017 (Random Forest)')
ax[0].set_xlabel('Precio Observado (Millones AUD)')
ax[0].set_ylabel('Precio Predicho (Millones AUD)')
ax[0].legend()

# Gráfico 2: Distribución de Residuos
sns.histplot(residuos / 1e3, kde=True, ax=ax[1], color='coral', bins=50)
ax[1].axvline(0, color='black', linestyle='--', linewidth=1.5)
ax[1].set_title('Distribución de Residuos de Predicción (Test 2017)')
ax[1].set_xlabel('Error de Predicción: Real - Predicho (Miles AUD)')
ax[1].set_ylabel('Frecuencia')

plt.tight_layout()
plt.show()


# 9. IMPORTANCIA RELATIVA DE VARIABLES (FEATURE IMPORTANCE)

# ¿Qué variables explican las predicciones?
# Se analiza la importancia por reducción de impureza (*Gini / MCO split*) del ensamble.


# 9.1. Extracción y Graficación de Feature Importance
rf_regresor = rf_modelo.named_steps['reg']
cat_encoder = rf_modelo.named_steps['prep'].named_transformers_['cat'].named_steps['encoder']
cat_features_nombres = cat_encoder.get_feature_names_out(variables_categoricas).tolist()
todos_features = variables_numericas + cat_features_nombres

importancias = rf_regresor.feature_importances_
df_importancias = (
    pd.DataFrame({'Variable': todos_features, 'Importancia': importancias})
    .sort_values(by='Importancia', ascending=False)
    .head(10)
)

plt.figure(figsize=(10, 5))
sns.barplot(data=df_importancias, x='Importancia', y='Variable', palette='Blues_r')
plt.title('Top 10 Variables con Mayor Importancia Predictiva (Random Forest)')
plt.xlabel('Importancia Relativa')
plt.ylabel('Atributo')
plt.show()


# 10. EJEMPLOS REALES DE PREDICCIÓN (TEST 2017)

# ¿Qué significan estos errores en la práctica?
# Se auditan 5 transacciones de 2017 comparando precio real, predicción y error porcentual.


ejemplos = X_test.copy().head(5)
ejemplos['Precio_Real'] = y_test.head(5)
ejemplos['Precio_Predicho'] = rf_modelo.predict(X_test.head(5)).round(0)
ejemplos['Error_Absoluto'] = (ejemplos['Precio_Real'] - ejemplos['Precio_Predicho']).abs()
ejemplos['Error_Relativo_(%)'] = ((ejemplos['Error_Absoluto'] / ejemplos['Precio_Real']) * 100).round(2)

print('Ejemplos Reales de Predicción en Melbourne 2017:')
print(ejemplos[['Habitaciones', 'Tipo', 'Distancia', 'Región', 'Precio_Real', 'Precio_Predicho', 'Error_Absoluto', 'Error_Relativo_(%)']].to_string())


# 11. CONCLUSIONES Y LIMITACIONES

# Conclusiones Principales:
# 1. Rechazo de la Hipótesis Nula ($H_0$):** Se refuta $H_0$. Las relaciones aprendidas en 2016 poseen suficiente consistencia para predecir precios en 2017 con un $R^2 = 0,7158$, superando holgadamente la mediana base ($R^2 = 0$).
# 2. Factores dominantes:** La tipología estructural (`Habitaciones`, `Baños`), combinada con la distancia al distrito financiero (`Distancia`) y las coordenadas geográficas, explican la mayor parte de la formación del precio.
# 3. Limitaciones reconocidas:** El modelo tiende a subestimar propiedades sobre los \$3.000.000 AUD (distribución con colas pesadas) y sufre un leve ensanchamiento del error en los 172 barrios no observados en 2016.

"""
### 12.3.1. Optimización de Hiperparámetros para Random Forest (GridSearchCV)

Vamos a utilizar `GridSearchCV` para encontrar la mejor combinación de hiperparámetros para el modelo `RandomForestRegressor`. Esto nos permitirá mejorar el rendimiento del modelo más allá de la configuración inicial."""

from sklearn.model_selection import GridSearchCV

# Definimos el pipeline para Random Forest
rf_pipeline = Pipeline(
    steps=[
        ('prep', preprocesador),
        ('reg', RandomForestRegressor(random_state=RANDOM_STATE))
    ]
)

# Definimos el rango de hiperparámetros a buscar
param_grid_rf = {
    'reg__n_estimators': [100, 200, 300], # Número de árboles en el bosque
    'reg__max_depth': [10, 15, 20],      # Profundidad máxima de los árboles
    'reg__min_samples_leaf': [5, 10, 20] # Número mínimo de muestras requeridas para estar en un nodo hoja
}

print("Iniciando GridSearchCV para RandomForestRegressor...")

# Configuramos GridSearchCV
# 'neg_mean_absolute_error' es la métrica que queremos minimizar
grid_search_rf = GridSearchCV(
    rf_pipeline,
    param_grid_rf,
    cv=cv, # Usamos la misma validación cruzada definida anteriormente
    scoring='neg_mean_absolute_error', # Se optimiza MAE (negativo para GridSearchCV)
    n_jobs=-1,
    verbose=2 # Mostrar el progreso
)

# Ejecutamos la búsqueda en el conjunto de entrenamiento
grid_search_rf.fit(X_train, y_train)

print("\nGridSearchCV completado.")
print(f"Mejores hiperparámetros encontrados: {grid_search_rf.best_params_}")
print(f"Mejor MAE (negativo) en CV: {grid_search_rf.best_score_:.2f}")
print(f"Mejor MAE (positivo) en CV: {-grid_search_rf.best_score_:.2f} AUD")

"""### 12.3.2. Evaluación del Modelo Random Forest Optimizado

Una vez que `GridSearchCV` ha encontrado los mejores hiperparámetros, evaluamos el rendimiento del modelo optimizado en el conjunto de prueba de 2017.
"""

import pandas as pd

# Obtenemos el mejor modelo
best_rf_model = grid_search_rf.best_estimator_

# Realizamos predicciones en el conjunto de prueba (2017)
y_pred_best_rf = best_rf_model.predict(X_test)

# Calculamos las métricas de evaluación
r2_test_optimized = r2_score(y_test, y_pred_best_rf)
mae_test_optimized = mean_absolute_error(y_test, y_pred_best_rf)
rmse_test_optimized = np.sqrt(mean_squared_error(y_test, y_pred_best_rf))

print("\n--- Métricas del Random Forest Optimizado (Test 2017) ---")
print(f"R² Test (2017): {r2_test_optimized:.4f}")
print(f"MAE Test ($): {mae_test_optimized:.2f}")
print(f"RMSE Test ($): {rmse_test_optimized:.2f}")

# Calculamos métricas para el conjunto de entrenamiento para la tabla
y_pred_train_optimized = best_rf_model.predict(X_train)
r2_train_optimized = r2_score(y_train, y_pred_train_optimized)

# Calculamos el R² de CV para el mejor modelo optimizado
# Usamos cross_val_score directamente sobre el best_rf_model para obtener el R2 de CV
scores_cv_optimized = cross_val_score(
    best_rf_model, X_train, y_train, cv=cv, scoring='r2', n_jobs=-1
)
cv_r2_optimized = scores_cv_optimized.mean()

# Añadimos este resultado a la tabla comparativa
resultados_lista.append({
    'Modelo': 'Random Forest Optimizado',
    'R² CV (Train 16)': round(cv_r2_optimized, 4),
    'R² Train': round(r2_train_optimized, 4),
    'R² Test (2017)': round(r2_test_optimized, 4),
    'MAE Test ($)': round(mae_test_optimized, 2),
    'RMSE Test ($)': round(rmse_test_optimized, 2),
    'Δ R² (Train-Test)': round(r2_train_optimized - r2_test_optimized, 4),
})

tabla_resultados_updated = pd.DataFrame(resultados_lista)
print('\n================ TABLA COMPARATIVA DE DESEMPEÑO ACTUALIZADA ================')
print(tabla_resultados_updated.to_string(index=False))

"""# 12. Mejoras para Alcanzar el 100%

Para elevar este proyecto a un nivel de excelencia total (100%), se recomienda profundizar en las siguientes áreas, demostrando no solo una ejecución técnica sólida, sino también una comprensión crítica y estratégica del problema de modelado:

### 12.1. EDA Avanzado y Justificación de Decisiones (Profundización)

Expandir el análisis exploratorio de datos para incluir:

*   **Análisis Univariado Exhaustivo:** Realizar una inspección detallada de la distribución de cada variable numérica clave (ej., `Distancia`, `Tamaño_Tierra`, `Latitud`, `Longitud`, `Cantidad_Propiedades`, `Habitaciones`, `Baños`, `Automóviles`) utilizando histogramas, diagramas de densidad (KDE) y box plots. Analizar formalmente su asimetría, curtosis y la presencia de *outliers*. Para las variables categóricas, presentar tablas de frecuencia o gráficos de barras para entender su distribución. **Justificar** por qué algunas visualizaciones se muestran o no en el informe final, pero demostrar que el análisis fue exhaustivo.
*   **Análisis Bivariado (Característica-Target):** Visualizar la relación de cada característica importante con la variable objetivo (`Precio`). Esto puede incluir scatter plots para variables numéricas (con líneas de regresión si aplica) y box plots o violin plots para variables categóricas. Esto ayuda a confirmar supuestos, identificar relaciones no lineales y evaluar el poder predictivo individual de cada característica.
*   **Tratamiento de Outliers:** Documentar explícitamente la estrategia de detección y manejo de *outliers*. ¿Se eliminaron, se transformaron (ej., `log` o `sqrt`), o se optó por mantenerlos como representativos de la población? La justificación debe ser sólida y basada en el dominio del problema.
*   **Análisis de Multicolinealidad:** Generar y analizar un mapa de calor de la matriz de correlación entre todas las variables numéricas seleccionadas. Esto permitirá identificar no solo redundancias obvias (como `Habitaciones` y `Habitaciones2` ya identificada), sino también relaciones de multicolinealidad menos evidentes que podrían afectar la estabilidad de modelos lineales.

### 12.2. Ingeniería de Características (Feature Engineering) - Creatividad y Riqueza

Demostrar la capacidad de crear nuevas características significativas que capturen información latente en los datos:

*   **Características de Interacción:** Generar nuevas variables que representen la interacción entre dos o más características existentes. Por ejemplo, la interacción entre `Distancia` y `Habitaciones`, o `Tamaño_Tierra` y `Tipo` de propiedad, puede capturar efectos sinérgicos que impactan el precio.
*   **Características Polinómicas:** Evaluar la posibilidad de aplicar transformaciones polinómicas a variables numéricas que muestren una relación no lineal con el `Precio`. Esto puede mejorar el ajuste del modelo, especialmente para modelos lineales.
*   **Características Temporales Detalladas:** Si la granularidad de la `Fecha` lo permite y si el rango temporal fuera más extenso, se podría explorar la creación de características como el `día_de_la_semana`, `mes`, o `trimestre` para capturar patrones estacionales o cíclicos no lineales.
*   **Características Geográficas Más Complejas:** Dado el problema de *covariate shift* con los barrios, se podría investigar la creación de características de agregación espacial. Por ejemplo, calcular la **densidad de propiedades** o el **precio promedio de ventas en un radio** determinado alrededor de cada propiedad. También se podría explorar la creación de **clústeres geográficos** de barrios con características socioeconómicas o de precios similares.

### 12.3. Optimización de Modelos (Hyperparameter Tuning)

La selección manual de hiperparámetros es un buen punto de partida, pero la optimización sistemática es clave:

*   **Búsqueda Sistemática de Hiperparámetros:** Implementar técnicas de optimización como `GridSearchCV` o `RandomizedSearchCV` (o alternativas más avanzadas como la optimización bayesiana) para encontrar la combinación óptima de hiperparámetros para los modelos con mejor rendimiento (ej., `RandomForestRegressor`, `GradientBoostingRegressor`). Esta búsqueda debe realizarse utilizando validación cruzada **exclusivamente sobre el conjunto de entrenamiento (2016)**.
*   **Justificación y Metodología de Búsqueda:** Documentar claramente el espacio de búsqueda para los hiperparámetros, la métrica de optimización utilizada (ej., `neg_mean_absolute_error` o `r2`), y por qué se eligieron esos rangos. Presentar los resultados de la búsqueda y la mejora obtenida.
*   **Análisis de la Sensibilidad:** Una breve discusión sobre cómo la variación de los hiperparámetros clave impacta el rendimiento del modelo puede demostrar una comprensión más profunda.

### 12.4. Análisis de Errores y Robustez (Profundización Crítica)

Ir más allá del diagnóstico básico de residuos para entender las limitaciones del modelo:

*   **Análisis de Errores por Segmento:** Investigar si el modelo exhibe patrones de error sistemáticos en subconjuntos específicos de los datos. Por ejemplo:
    *   **Residuos vs. Predicciones:** Un scatter plot de `Residuos` vs. `y_pred` puede indicar heterocedasticidad o sesgos en diferentes rangos de precios.
    *   **Residuos vs. Características Clave:** Visualizar los residuos frente a variables predictoras importantes (ej., `Distancia`, `Habitaciones`, `Tipo`, `Región`) para detectar si el modelo subestima o sobrestima consistentemente en ciertos segmentos del mercado.
    *   **Análisis del Rendimiento en Barrios Nuevos (Covariate Shift):** Dado el hallazgo de 172 barrios nuevos en 2017, analizar específicamente el rendimiento del modelo (MAE, RMSE, R²) en estas propiedades comparado con los barrios que sí estaban presentes en 2016. Esto cuantificará el impacto del *covariate shift* y validará las decisiones de diseño tomadas para mitigarlo.
*   **Métricas Adicionales:** Considerar otras métricas relevantes para la evaluación, como el **MAPE** (Mean Absolute Percentage Error), si la interpretabilidad del error en términos porcentuales es de interés para las partes interesadas.

### 12.5. Consideraciones de Despliegue y Ética (Visión Global)

Aunque no es directamente una tarea de codificación, una discusión reflexiva sobre estos puntos demuestra una comprensión integral del ciclo de vida del aprendizaje automático:

*   **Despliegue Conceptual del Modelo:** Describir brevemente cómo se podría poner este modelo en producción. ¿Qué tecnologías o plataformas se usarían? ¿Cuáles serían los principales desafíos técnicos (ej., latencia, escalabilidad)?
*   **Monitoreo del Modelo:** Proponer un plan para monitorear el rendimiento del modelo una vez desplegado. ¿Qué métricas de negocio y técnicas se usarían? ¿Cómo se detectaría la **deriva de datos (data drift)** o la **deriva del modelo (model drift)**? ¿Con qué frecuencia se re-entrenaría el modelo y con qué tipo de datos?
*   **Implicaciones Éticas y Sesgos:** Reflexionar sobre posibles sesgos inherentes a los datos históricos o al propio modelo que podrían llevar a tasaciones injustas o discriminatorias. Discutir posibles estrategias para identificar y mitigar estos sesgos, garantizando un uso responsable del modelo predictivo.

Implementar y documentar estas mejoras no solo optimizará el rendimiento del modelo, sino que también demostrará una maestría en el arte y la ciencia de la construcción de soluciones de datos robustas y confiables.

### Análisis y Resumen del Trabajo

Este proyecto aborda la **predicción del valor de propiedades inmobiliarias en Melbourne**, utilizando un enfoque de **aprendizaje supervisado de regresión**. La particularidad y desafío clave radica en la **validación temporal estricta**: los modelos se entrenan exclusivamente con datos de transacciones de 2016 y se evalúan en datos de 2017, simulando una predicción en un escenario futuro y real. La variable objetivo es el `Precio` de las propiedades.

**1. Metodología para el Ajuste de Modelos:**

*   **Carga y Preprocesamiento de Datos:** Se cargó el archivo `housing_data.csv`. Las columnas fueron renombradas a español y algunas categorías (`Tipo`, `Método`) fueron homogeneizadas. La columna `Fecha` se convirtió a tipo datetime y se extrajo el `Year` (año) para la partición temporal.
*   **Análisis Exploratorio de Datos (EDA):** Se identificaron valores nulos significativos, especialmente en `Tamaño_Construcción`, `Año_Construcción`, y `Comuna`, lo que llevó a su descarte para evitar pérdida excesiva de datos o imputaciones arbitrarias. También se detectó una asimetría positiva en la distribución del `Precio` y una redundancia entre `Habitaciones` y `Habitaciones2` (descartándose esta última). Un hallazgo crítico fue el **desplazamiento geográfico (Covariate Shift)** en 2017, con 172 barrios nuevos no vistos en 2016, lo que motivó el uso de variables espaciales continuas (`Distancia`, `Latitud`, `Longitud`) y la `Región` categórica para la ubicación.
*   **Partición Temporal Estricta:** La base de datos se dividió rigurosamente: 2016 para el conjunto de entrenamiento (`X_train`, `y_train`) y 2017 para el conjunto de prueba (`X_test`, `y_test`). Esto asegura que el modelo no vea datos futuros durante el entrenamiento, previniendo el *data leakage*.
*   **Pipeline de Preprocesamiento:** Se construyó un `ColumnTransformer` para encapsular el preprocesamiento, aplicando transformaciones específicas para variables numéricas y categóricas. Para las numéricas, se utilizó `SimpleImputer(strategy='median')` y `StandardScaler`. Para las categóricas, `SimpleImputer(strategy='constant', fill_value='missing')` y `OneHotEncoder(handle_unknown='ignore', sparse_output=False)`. Es crucial que la imputación y el escalado aprendan sus parámetros solo del conjunto de entrenamiento para evitar filtraciones de información.
*   **Modelos Evaluados:** Se definieron y evaluaron cinco modelos predictivos:
    *   **Baseline:** `DummyRegressor(strategy='median)` para establecer una referencia.
    *   **Regresión Lineal:** Un modelo lineal paramétrico.
    *   **Árbol de Decisión:** Un modelo no lineal.
    *   **Random Forest Regressor:** Un ensamble de *bagging*.
    *   **Gradient Boosting Regressor:** Un ensamble de *boosting*.
*   **Validación y Evaluación:** Se realizó una validación cruzada (K=5) en el conjunto de entrenamiento de 2016 para evaluar la estabilidad interna. Finalmente, los modelos se ajustaron con la totalidad de los datos de 2016 y se evaluaron en el conjunto de prueba de 2017 utilizando métricas como R², Error Absoluto Medio (MAE) y Error Cuadrático Medio (RMSE).

**2. Resultados Obtenidos y Conclusión del Trabajo:**

La **tabla comparativa de desempeño** muestra claramente la mejora de los modelos de aprendizaje automático sobre el baseline. El `Gradient Boosting` obtuvo el mejor rendimiento en el conjunto de prueba de 2017 con un **R² de 0.7191**, un **MAE de $205,546.03 AUD** y un **RMSE de $333,755.14 AUD**. El `Random Forest`, aunque ligeramente inferior en `R² Test`, también demostró un desempeño robusto.

La sección 8 del código selecciona **Random Forest** como el modelo final debido a su **capacidad predictiva superior** (mayor R² en Test, minimiza MAE), la **reducción sustancial del error** frente al baseline (47.2% de reducción del MAE), y su **estabilidad y capacidad de generalización**, especialmente frente al desplazamiento geográfico observado en 2017. Los diagnósticos gráficos (Valor Observado vs. Predicho, Distribución de Residuos) y el análisis de importancia de características refuerzan esta selección, mostrando que `Habitaciones`, `Región_Southern Metropolitan`, `Distancia` y `Tamaño_Tierra` son las variables más predictivas.

**Conclusiones Principales (según el análisis del código):**
1.  **Rechazo de la Hipótesis Nula:** Los modelos, particularmente el Random Forest, demostraron una capacidad predictiva significativa para los precios de 2017 basándose en datos de 2016, superando ampliamente al baseline.
2.  **Factores Dominantes:** Las características estructurales (`Habitaciones`, `Baños`), la distancia al centro financiero (`Distancia`) y las coordenadas geográficas (`Latitud`, `Longitud`), junto con la `Región` y el `Tipo` de propiedad, son los principales impulsores del precio.
3.  **Limitaciones:** El modelo tiende a subestimar propiedades de alto valor (superiores a $3,000,000 AUD) y puede mostrar un ligero aumento del error en barrios que no fueron observados durante el entrenamiento (los 172 barrios nuevos de 2017).

### Gráficos Recomendados

Además de los excelentes gráficos ya implementados (observado vs. predicho, distribución de residuos e importancia de características), te sugiero los siguientes para un análisis más completo:

1.  **Distribución de la Variable Objetivo (`Precio`) por Año (Histogramas o KDE):**
    *   **Justificación:** Visualizar la distribución de los precios en 2016 (entrenamiento) y 2017 (prueba) ayudará a confirmar la asimetría positiva mencionada en el EDA y a detectar posibles cambios en la distribución de precios entre ambos años que podrían explicar algunas limitaciones del modelo.
    *   **Código Sugerido:**
"""

plt.figure(figsize=(12, 5))
sns.histplot(df[df['Year'] == 2016]['Precio'], kde=True, color='skyblue', label='2016 (Train)', stat='density', alpha=0.6)
sns.histplot(df[df['Year'] == 2017]['Precio'], kde=True, color='salmon', label='2017 (Test)', stat='density', alpha=0.6)
plt.title('Distribución de Precios por Año')
plt.xlabel('Precio (AUD)')
plt.ylabel('Densidad')
plt.legend()
plt.show()

"""2.  **Box Plots/Violin Plots de Precio por Categoría Principal:**
    *   **Justificación:** Explorar visualmente cómo categorías clave como `Tipo` y `Región` se relacionan con el precio. Esto puede ofrecer información adicional sobre la heterogeneidad de los precios entre diferentes segmentos del mercado.
    *   **Código Sugerido:**

"""

plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
sns.boxplot(x='Tipo', y='Precio', data=df, palette='viridis')
plt.title('Precio por Tipo de Propiedad')
plt.xlabel('Tipo de Propiedad')
plt.ylabel('Precio (AUD)')
plt.ticklabel_format(style='plain', axis='y') # Evita notación científica

plt.subplot(1, 2, 2)
sns.boxplot(x='Región', y='Precio', data=df, palette='cividis')
plt.title('Precio por Región')
plt.xlabel('Región')
plt.ylabel('Precio (AUD)')
plt.xticks(rotation=45, ha='right')
plt.ticklabel_format(style='plain', axis='y')

plt.tight_layout()
plt.show()

"""3.  **Gráfico de Serie Temporal del Precio Medio (si hubiera datos diarios/mensuales):**
    *   **Justificación:** Aunque la partición es por año, una visualización del precio promedio a lo largo del tiempo (si el `Date` tuviera más granularidad) podría revelar tendencias o patrones estacionales dentro de cada año, lo cual no es directamente visible con la agregación anual. Si el dataset es muy corto, esto podría no ser muy informativo.
    *   **Código Sugerido (asumiendo `df['Fecha']` está en formato datetime):**

"""

df['Mes_Año'] = df['Fecha'].dt.to_period('M')
precio_medio_mensual = df.groupby('Mes_Año')['Precio'].mean().reset_index()
precio_medio_mensual['Mes_Año'] = precio_medio_mensual['Mes_Año'].astype(str)

plt.figure(figsize=(12, 6))
sns.lineplot(x='Mes_Año', y='Precio', data=precio_medio_mensual)
plt.title('Precio Medio de Propiedades por Mes y Año')
plt.xlabel('Mes y Año')
plt.ylabel('Precio Medio (AUD)')
plt.xticks(rotation=45)
plt.grid(True)
plt.show()